table bigPrimerBed
"BigBed schema for Primer JuJu primer pairs"
    (
    string chrom;      "Chromosome"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Name of item"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick"
    uint thickEnd;     "End of where display should be thick"
    uint reserved;     "itemRgb"
    int blockCount;    "Number of blocks"
    int[blockCount] blockSizes; "Comma separated list of block sizes"
    int[blockCount] chromStarts; "Start positions relative to chromStart"
    int    PRIMER_PAIR_PRODUCT_SIZE;      "PRIMER_PAIR_PRODUCT_SIZE       1133"
    float  PRIMER_PAIR_COMPL_ANY_TH;      "PRIMER_PAIR_COMPL_ANY_TH       12.49"
    float  PRIMER_PAIR_COMPL_END_TH;      "PRIMER_PAIR_COMPL_END_TH       5.03"
    float  PRIMER_PAIR_PENALTY;           "PRIMER_PAIR_PENALTY            0.42"
    string PRIMER_LEFT;                   "PRIMER_LEFT                    (27, 20)"
    string PRIMER_LEFT_SEQUENCE;          "PRIMER_LEFT_SEQUENCE           'GGTTCTTCTGCGCTACTGCT'"
    float  PRIMER_LEFT_END_STABILITY;     "PRIMER_LEFT_END_STABILITY      4.24"
    float  PRIMER_LEFT_GC_PERCENT;        "PRIMER_LEFT_GC_PERCENT         55.0"
    float  PRIMER_LEFT_HAIRPIN_TH;        "PRIMER_LEFT_HAIRPIN_TH         36.97"
    float  PRIMER_LEFT_PENALTY;           "PRIMER_LEFT_PENALTY            0.39"
    float  PRIMER_LEFT_SELF_ANY_TH;       "PRIMER_LEFT_SELF_ANY_TH        9.73"
    float  PRIMER_LEFT_SELF_END_TH;       "PRIMER_LEFT_SELF_END_TH        0.0"
    float  PRIMER_LEFT_TM;                "PRIMER_LEFT_TM                 60.39"
    string PRIMER_RIGHT;                  "PRIMER_RIGHT                   (1159, 20)"
    string PRIMER_RIGHT_SEQUENCE;         "PRIMER_RIGHT_SEQUENCE          'CAAAAACCCACGCAGACAGG'"
    float  PRIMER_RIGHT_END_STABILITY;    "PRIMER_RIGHT_END_STABILITY     4.0"
    float  PRIMER_RIGHT_GC_PERCENT;       "PRIMER_RIGHT_GC_PERCENT        55.0"
    float  PRIMER_RIGHT_HAIRPIN_TH;       "PRIMER_RIGHT_HAIRPIN_TH        0.0"
    float  PRIMER_RIGHT_PENALTY;          "PRIMER_RIGHT_PENALTY           0.030"
    float  PRIMER_RIGHT_SELF_ANY_TH;      "PRIMER_RIGHT_SELF_ANY_TH       0.0"
    float  PRIMER_RIGHT_SELF_END_TH;      "PRIMER_RIGHT_SELF_END_TH       0.0"
    float  PRIMER_RIGHT_TM;               "PRIMER_RIGHT_TM                59.96"
    )
